language: python
python:
  - "3.8"

cache: pip

install:
  - pip install -r requirements.txt
  - pip install notebook

script: jupyter nbconvert --execute *.ipynb && python -m pension && python -m unittest
